"""initial schema

Revision ID: 9e055cb32e5f
Revises: 
Create Date: 2026-07-29 02:47:54.622198
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9e055cb32e5f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('device_label', sa.String(length=120), nullable=True),
    sa.Column('conf_threshold', sa.Float(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('defect_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('defect_count <= total_count', name='ck_sessions_defect_lte_total'),
    sa.CheckConstraint('defect_count >= 0', name='ck_sessions_defect_nonneg'),
    sa.CheckConstraint('total_count >= 0', name='ck_sessions_total_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'batch_id', name='uq_sessions_user_batch')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('idx_sessions_user', ['user_id', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_uuid'), ['uuid'], unique=True)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fig_seq', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.CheckConstraint("decision IN ('Healthy', 'Aflatoxin')", name='ck_inspections_decision'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_inspections_confidence'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'fig_seq', name='uq_inspections_session_seq')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index('idx_insp_decision', ['session_id', 'decision'], unique=False)
        batch_op.create_index('idx_insp_session', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index('idx_insp_session')
        batch_op.drop_index('idx_insp_decision')

    op.drop_table('inspections')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_uuid'))
        batch_op.drop_index('idx_sessions_user')

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
